apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: "torchserve"
spec:
  predictor:
    pytorch:
      protocolVersion: v2
      storageUri: "pvc://model-pv-claim"
      resources:
        limits:
          cpu: 16
          memory: 16Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: 8
          memory: 16Gi
          nvidia.com/gpu: "1"
 