apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: "torchserve"
spec:
  predictor:
    pytorch:
      protocolVersion: v2
      storageUri: "pvc://model-pv-claim"
      resources:
        limits:
          nvidia.com/gpu: 1
