apiVersion: serving.kubeflow.org/v1beta1
kind: InferenceService
metadata:
  name: "torchserve"
spec:
  predictor:
    pytorch:
      protocolVersion: v2
      storageUri: gs://kfserving-examples/models/torchserve/image_classifier
      # storageUri: pvc://model-pv-claim
      resources:
        limits:
          memory: 4Gi
