apiVersion: serving.kubeflow.org/v1beta1
kind: InferenceService
metadata:
  name: torchserve
spec:
  transformer:
    containers:
      - image: <username>/image-transformer:latest
        name: transformer-container
        env:
          - name: STORAGE_URI
            value: pvc://model-pv-claim
  predictor:
    pytorch:
      protocolVersion: v2
      storageUri: pvc://model-pv-claim
      runtimeVersion: v1.2-gpu
