apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-pv-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
      - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-074ea8934f7b80df5
    fsType: ext4
