apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: torchserve-custom
spec:
  predictor:
    canaryTrafficPercent: 10
    containers:
    - image: jagadeeshj/ts_custom:v1.0
      name: torchserve-container
      ports:
        - containerPort: 8080
